name: Ruby

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.1-alpine
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Install Yarn
        run: yarn --frozen-lockfile
      - name: Create Evaluation File
        run: |
          rm -rf spec
          echo -e "---\ntitle: ブランチ名に誤りがあり、評価できません。\n---\n課題の評価が可能なブランチ名：step1、step2、step3、step4、step5" > .github/branch_error.md
          git clone https://github.com/kei-kamiguchi/spec_test.git spec
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add Spec Test"
      - name: Test with RSpec at Step1
        if: contains(github.ref, 'step1')
        env:
          RAILS_ENV: "test"
          DATABASE_URL: "postgres://postgres@localhost:5432/manyo_test"
        run: |
          bundle exec rails db:setup
          bundle exec rspec -r ./spec/my_formatter.rb -f MyFormatter spec/system/tasks_spec.rb -o .github/issue_template_link_check.md
        continue-on-error: true
      - name: Test with RSpec at Step2
        if: contains(github.ref, 'step2')
        env:
          RAILS_ENV: "test"
          DATABASE_URL: "postgres://postgres@localhost:5432/manyo_test"
        run: |
          bundle exec rails db:setup
          bundle exec rspec -r ./spec/my_formatter.rb -f MyFormatter spec/system/tasks_spec.rb -o .github/issue_template_link_check.md
        continue-on-error: true
      - name: Test with RSpec at Step3
        if: contains(github.ref, 'step3')
        env:
          RAILS_ENV: "test"
          DATABASE_URL: "postgres://postgres@localhost:5432/manyo_test"
        run: |
          bundle exec rails db:setup
          bundle exec rspec -r ./spec/my_formatter.rb -f MyFormatter spec/system/tasks_spec.rb -o .github/issue_template_link_check.md
        continue-on-error: true
      - name: Test with RSpec at Step4
        if: contains(github.ref, 'step4')
        env:
          RAILS_ENV: "test"
          DATABASE_URL: "postgres://postgres@localhost:5432/manyo_test"
        run: |
          bundle exec rails db:setup
          bundle exec rspec -r ./spec/my_formatter.rb -f MyFormatter spec/system/tasks_spec.rb -o .github/issue_template_link_check.md
        continue-on-error: true
      - name: Test with RSpec at Step5
        if: contains(github.ref, 'step5')
        env:
          RAILS_ENV: "test"
          DATABASE_URL: "postgres://postgres@localhost:5432/manyo_test"
        run: |
          bundle exec rails db:setup
          bundle exec rspec -r ./spec/my_formatter.rb -f MyFormatter spec/system/tasks_spec.rb -o .github/issue_template_link_check.md
        continue-on-error: true
      - uses: JasonEtco/create-an-issue@v2
        if: contains(github.ref, 'step1') || contains(github.ref, 'step2') || contains(github.ref, 'step3') || contains(github.ref, 'step4') || contains(github.ref, 'step5')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/issue_template_link_check.md
      - uses: JasonEtco/create-an-issue@v2
        if: "!contains(github.ref, 'step1') && !contains(github.ref, 'step2') && !contains(github.ref, 'step3') && !contains(github.ref, 'step4') && !contains(github.ref, 'step5')"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/branch_error.md
